### ISSUE TITLE
Run documentation removed?

### ISSUE THREAD

**Issue by WKNiGHT-** [FredericGodest/CryptoBot#2]
Looks like a lot of new code which is wonderful. However, when trying to run the code i am not sure where you want the config information.

Traceback (most recent call last):
  File "/home/ubuntu/bot_addons/CryptoBot/main.py", line 21, in <module>
    bot_token = config['TOKEN_BOT']
KeyError: 'TOKEN_BOT'

**Comment by WKNiGHT-** [comment]
I commented out some code for the test env and it now works

**Comment by FredericGodest** [comment]
Perfect :) if you want to do a pull request you are welcome :)
