### ISSUE TITLE
another error

### ISSUE THREAD

**Issue by WKNiGHT-** [FredericGodest/CryptoBot#3]
Not sure if its because I am guessing where to add the bot_tokens and or maybe channel configuration. Would it be possible to put in some comments on where to put those settings

  File "/home/ubuntu/.local/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/bot_addons/CryptoBot/main.py", line 79, in on_ready
    channel = client.get_channel(int(weekly_crypto))
NameError: name 'weekly_crypto' is not defined
Crypto Bot Connected !

**Comment by FredericGodest** [comment]
Yes of course! These informations are not available because I originaly done this project for myself. If you Want to add comment to your fork it's ok :)

**Comment by WKNiGHT-** [comment]
Just wanted to say it is such a neat project. Thank you for sharing it. Go my first alert setup so it was pretty cool to see that. JUst needed to learn setting up the env and stuff :) . Keep up the great work!

**Comment by FredericGodest** [comment]
Thanks, I will check your fork and eventually merge it to the main/master branch !
